const light = {
  background:           '#FFFFFF',
  groupedBackground:    '#F2F2F7',
  secondaryBackground:  '#F2F2F7',
  surface:              '#FFFFFF',
  elevatedSurface:      '#FFFFFF',
  foreground:           '#000000',
  label:                '#000000',
  secondaryLabel:       'rgba(60,60,67,0.6)',
  tertiaryLabel:        'rgba(60,60,67,0.3)',
  muted:                'rgba(60,60,67,0.6)',
  separator:            'rgba(60,60,67,0.29)',
  opaqueSeparator:      '#C6C6C8',
  border:               '#E5E5EA',
  fill:                 'rgba(120,120,128,0.2)',
  secondaryFill:        'rgba(120,120,128,0.16)',
  primary:              '#007AFF',
  primaryForeground:    '#FFFFFF',
  accent:               '#007AFF',
  card:                 '#FFFFFF',
  tabBar:               'rgba(249,249,249,0.94)',
  tabBarBorder:         'rgba(0,0,0,0.12)',
  success:              '#34C759',
  successBg:            '#E8F8ED',
  error:                '#FF3B30',
  errorBg:              '#FFECEB',
  warning:              '#FF9500',
  warningBg:            '#FFF3E0',
  violet:               '#AF52DE',
  violetBg:             '#F5EEFA',
  radius:               10,
  shadow: {
    color: '#000',
    offset: { width: 0, height: 1 },
    opacity: 0.08,
    radius: 6,
    elevation: 2,
  },
} as const;

export const colors = { light };
export type ColorScheme = typeof light;
