// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/inkbook/Browse.tsx": () => import("../components/mockups/inkbook/Browse.tsx"),
  "./components/mockups/inkbook/StudioDetail.tsx": () => import("../components/mockups/inkbook/StudioDetail.tsx")
};
